dispatch:
  accessAddress: 127.0.0.1:8080
  language: zh_CN
  gateServer:
    - name: http
      title: http
      dispatchUrl: http://127.0.0.1:8080/query_cur_region
    - name: https
      title: https
      dispatchUrl: https://127.0.0.1:443/query_cur_region
    - name: foobar
      title: foobar
      ip: 127.0.0.1
      port: 22102
