server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:secret/ssl/keystore.p12
    key-store-password: 123456

spring:
  profiles:
    include: dispatch
  application:
    name: ${rootProject.name}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.office365.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: no-reply@account.casks.me
    password: CASKSme123

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.tianli.dispatch.domain

logging:
  level:
    com.tianli.dispatch: debug
    org.springframework: WARN
